site_name: Benjy
repo_url: https://github.com/grai-io/benjy

nav:
    - Home: index.md
    - 'User Guide': 
        - 'Quick Start': user_guide/quick_start.md
        - Components: user_guide/components.md


markdown_extensions:
    - smarty
    - wikilinks
    - toc
    - admonition
    - sane_lists
    - codehilite
    - meta
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
    - search
    - mermaid2
    - mkdocstrings
    - macros
    - mkdocs-jupyter

theme:
    name: material
    logo: assets/icon-logo-0.svg